version: "3.8"

services:
  db:
    container_name: zoomysql-container
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_PASSWORD=111111
    ports:
      - "3307:3306"

  zoostoreapp:
    image: zoostore:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://zoomysql-container:3306/zoostoredatabase",
        "spring.datasource.username": "root",
        "spring.datasource.password": "111111",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'

  zoostorestorageapp:
    image: storage:latest
    depends_on:
      - db
      - zoostoreapp
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://zoomysql-container:3306/zoostorestorage",
        "spring.datasource.username": "root",
        "spring.datasource.password": "111111",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'

  zoobffapp:
    image: bff:latest
    depends_on:
      - db
      - zoostoreapp
      - zoostorestorageapp
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://zoomysql-container:3306/zoostoreuser",
        "spring.datasource.username": "root",
        "spring.datasource.password": "111111",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'






